'use client';

import UsagePanel from './UsagePanel';
import StoryLibrary from './StoryLibrary';
import ImageWorkflow from './ImageWorkflow';
import ModelConfig from './ModelConfig';
import {useCallback,useEffect,useRef,useState} from 'react';
import {BookOpen,Layers3,Film,Workflow,Settings2,ArrowUpRight,ArrowRight,Plus,Play,Pause,RotateCcw,Check,ChevronRight,Clock3,Upload,Download,LoaderCircle,AlertCircle,X,Scissors,ShieldCheck,Sparkles,VolumeX,GitBranch,Search,ChevronLeft,PanelRightClose} from 'lucide-react';

type Entry={clip_id:string,start:number,end:number};
type Clip={id:string,title:string,duration:number,media:string,narration:string,demo:boolean,status:string,events:{at:number,text:string,changes:Record<string,string>}[],draft_events?:{at:number,text:string,changes:Record<string,string>}[],reason?:string};
type Asset={id:string,name:string,type:string,description:string,palette:string,status:string,media:string,parent_id?:string};
type Plan={status:string,summary:string,preserved:string[],beats:{title:string,narration:string,reason:string,changes:Record<string,string>,duration:number}[],suggestions:string[]};
type Task={id:string,kind:string,status:string,session_id:string,revision:number,progress:number,message:string,result:{plan?:Plan,media?:string,provider_id?:string,clip_ids?:string[]},created:number,mode:string};
type Session={id:string,version:number,entries:Entry[],active_task:string|null,last_plan?:Plan};
type Config={image_configured:boolean,image_model:string,llm_configured:boolean,video_configured:boolean,llm_model:string,video_model:string,paid_enabled:boolean,paid_used:number};
type Bootstrap={story:{title:string,subtitle:string,synopsis:string,ending:string,constraints:string[],source:string},assets:Asset[],clips:Clip[],settings:Config,labels:Record<string,string>,values:Record<string,string>};
type History={id:string,text:string,index:number,offset:number,revision:number};
async function api<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api'+path,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){let msg='请求失败';try{const d=await r.json();msg=typeof d.detail==='string'?d.detail:JSON.stringify(d.detail);}catch{}throw new Error(msg);}return r.json();}
const time=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const statusName:Record<string,string>={queued:'排队中',running:'执行中',waiting:'等待供应商',completed:'已完成',failed:'未完成',needs_review:'需要处理',superseded:'已被替代',cancelled:'已停止',approved:'已通过',pending:'待审核',rejected:'已退回'};
const navs=[{id:'stories',label:'知乎故事库',icon:BookOpen},{id:'reader',label:'内部交互调试',icon:Play},{id:'studio',label:'原版制作',icon:Film},{id:'assets',label:'人物与场景',icon:Layers3},{id:'tasks',label:'工作流记录',icon:Workflow},{id:'settings',label:'模型连接',icon:Settings2}];

export default function Home(){
 const [tab,setTab]=useState('stories'),[data,setData]=useState<Bootstrap|null>(null),[session,setSession]=useState<Session|null>(null),[tasks,setTasks]=useState<Task[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false);
 const [index,setIndex]=useState(0),[offset,setOffset]=useState(0),[playing,setPlaying]=useState(false),[text,setText]=useState(''),[mode,setMode]=useState('demo'),[state,setState]=useState<Record<string,string>>({}),[history,setHistory]=useState<History[]>([]),[panel,setPanel]=useState('rewrite'),[assetFilter,setAssetFilter]=useState('all'),[query,setQuery]=useState('');
 const [assetEdit,setAssetEdit]=useState<Partial<Asset>|null>(null),[uploadBusy,setUploadBusy]=useState(false),[preview,setPreview]=useState<Clip|null>(null),[prompt,setPrompt]=useState('漫画风格，雨夜站台，米白风衣的短发女记者在立柱旁警惕地回头。中景，缓慢推进。'),[reference,setReference]=useState(''),[paidConfirm,setPaidConfirm]=useState(false);
 const video=useRef<HTMLVideoElement>(null),sessionRef=useRef<Session|null>(null),indexRef=useRef(0),initializing=useRef(false),renderSeen=useRef('');
 const [annotation,setAnnotation]=useState<Clip['events']>([]),[bridgeConfirm,setBridgeConfirm]=useState(false);
 const [autoRender,setAutoRender]=useState(true);
 const [showDemo,setShowDemo]=useState(false);
 const visibleClips=data?.clips.filter(c=>showDemo||!c.demo)||[];
 const [recovery,setRecovery]=useState<Record<string,string>>({});
 const continuePlayback=useRef(false);
 useEffect(()=>{setAnnotation(preview?.events.length?preview.events:preview?.draft_events||[]);},[preview]);
 useEffect(()=>{sessionRef.current=session;},[session]);useEffect(()=>{indexRef.current=index;},[index]);
 const refresh=useCallback(async()=>{const [d,t,h]=await Promise.all([api<Bootstrap>('/bootstrap'),api<Task[]>('/tasks'),api<{worker_online:boolean}>('/health')]);setData(d);setTasks(t);setConnected(h.worker_online);const current=sessionRef.current;if(current){const s=await api<Session>('/sessions/'+current.id);setSession(s);setHistory(await api<History[]>('/sessions/'+current.id+'/history'));}},[]);
 useEffect(()=>{if(initializing.current)return;initializing.current=true;(async()=>{try{await refresh();let s:Session;const saved=localStorage.getItem('storyloom-session');try{if(!saved)throw new Error();s=await api<Session>('/sessions/'+saved);}catch{s=await api<Session>('/sessions',{});localStorage.setItem('storyloom-session',s.id);}sessionRef.current=s;setSession(s);}catch(e){setError((e as Error).message+'。请确认后端已启动。');}})();},[refresh]);
 useEffect(()=>{const id=setInterval(()=>refresh().catch(()=>setConnected(false)),2500);return()=>clearInterval(id);},[refresh]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t);}},[notice]);
 const entries=session?.entries||[],entry=entries[index],clip=data?.clips.find(c=>c.id===entry?.clip_id),total=entries.reduce((n,e)=>n+e.end-e.start,0),elapsed=entries.slice(0,index).reduce((n,e)=>n+e.end-e.start,0)+Math.max(0,offset-(entry?.start||0));
 const activePlan=tasks.find(t=>t.session_id===session?.id&&t.kind==='plan'&&t.revision===session?.version),plan=activePlan?.result.plan;
 const activeRender=tasks.find(t=>t.session_id===session?.id&&t.kind==='render'&&['queued','running'].includes(t.status));
 const reviewBridge=tasks.find(t=>t.session_id===session?.id&&t.kind==='bridge'&&t.revision===session?.version&&t.status==='needs_review'&&t.result.clip_ids);
 useEffect(()=>{const done=tasks.find(t=>t.session_id===session?.id&&t.kind==='render'&&t.status==='completed');if(done&&renderSeen.current!==done.id&&session?.version===done.revision+1){renderSeen.current=done.id;setNotice('过渡片段已加入播放列表。你可以继续播放，也可以再次暂停改写。');}},[tasks,session]);
 async function getState(at=video.current?.currentTime??offset){if(!session)return;try{const d=await api<{state:Record<string,string>}>(`/sessions/${session.id}/state?index=${index}&offset=${at}`);setState(d.state);}catch(e){setError((e as Error).message);}}
 function pauseForEdit(){video.current?.pause();setPanel('rewrite');getState();document.getElementById('rewrite-input')?.focus();}
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function rewrite(){if(!session||!entry)return;video.current?.pause();await action(async()=>{const at=Math.min(entry.end,Math.max(entry.start,video.current?.currentTime??offset));const r=await api<{task:Task,session:Session}>(`/sessions/${session.id}/rewrite`,{version:session.version,index,offset:at,text,mode,auto_render:autoRender&&mode==='demo'});setSession(r.session);sessionRef.current=r.session;setState({});await refresh();setNotice(mode==='demo'?'已提交演示改写，正在规划衔接。':'已提交真实模型，开始规划与独立检查。');});}
 async function render(){if(!session||!activePlan)return;await action(async()=>{await api(`/sessions/${session.id}/render`,{plan_task_id:activePlan.id,version:session.version});await refresh();});}
 async function renderLive(){if(!session||!activePlan)return;await action(async()=>{await api(`/sessions/${session.id}/render`,{plan_task_id:activePlan.id,version:session.version,mode:'live',confirm_paid:paidConfirm});await refresh();setNotice('真实过渡已加入制作队列；完成后逐镜审核再接入。');});}
 function goTo(i:number){continuePlayback.current=false;video.current?.pause();setIndex(i);setOffset(entries[i].start);setState({});}
 async function reset(){await action(async()=>{const s=await api<Session>('/sessions',{});setSession(s);sessionRef.current=s;localStorage.setItem('storyloom-session',s.id);setIndex(0);setOffset(0);setState({});setText('');setNotice('已创建新的阅读分支，旧记录仍保留。');await refresh();});}
 async function review(id:string,status:string){await action(async()=>{await api('/review/'+id,{status,note:status==='approved'?'本地操作员确认':'请修改后重新提交'});await refresh();setNotice(status==='approved'?'审核状态已保存':'已退回修改');});}
 async function upload(file:File){const f=new FormData();f.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.detail||'上传失败');await refresh();return d.media as string;}
 async function saveAsset(){if(!assetEdit)return;await action(async()=>{await api(assetEdit.id?`/assets/${assetEdit.id}/fork`:'/assets',{name:assetEdit.name,type:assetEdit.type,description:assetEdit.description,media:assetEdit.media||''});setAssetEdit(null);await refresh();setNotice('已保存为待审核素材；原版素材保持原有版本。');});}
 const filteredAssets=data?.assets.filter(a=>(assetFilter==='all'||a.type===assetFilter)&&(a.name+a.description).includes(query))||[];

 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('reader');}}><span className="brand-mark"><BookOpen size={24}/></span><span>叙间<small>STORYLOOM</small></span></a>
   <div className="workspace-label">创作空间 <span>个人版</span></div><nav>{navs.map(n=><button key={n.id} className={tab===n.id?'nav active':'nav'} onClick={()=>{video.current?.pause();setTab(n.id);}}><n.icon size={18}/>{n.label}{n.id==='tasks'&&tasks.some(t=>['queued','running','waiting'].includes(t.status))&&<i className="activity-dot"/>}</button>)}</nav>
   {showDemo&&<div className="sidebar-story"><div className="tiny-label">正在探索的故事</div><div className="book-cover"><span>雨夜<br/>最后一班车</span><small>AN INTERACTIVE STORY</small></div><strong>雨夜最后一班车</strong><p>原创悬疑 · 技术演示</p><button onClick={()=>setTab('studio')}>查看作者主线 <ArrowUpRight size={14}/></button></div>}
   <div className="sidebar-bottom"><span className={'dot '+(connected?'green':'')}/><span>{connected?'后台工作流在线':'等待后台执行器'}</span><span className="version">v0.1</span></div>
  </aside>
  <UsagePanel/><main className="main"><header className="topbar"><div className="breadcrumb">工作空间 <ChevronRight size={13}/><span>{navs.find(n=>n.id===tab)?.label}</span></div><div className="top-actions"><label className="checkbox"><input type="checkbox" checked={showDemo} onChange={e=>{video.current?.pause();setShowDemo(e.target.checked);}}/>显示演示内容</label><button className="button secondary" onClick={()=>setTab('settings')} aria-label="模型设置">模型设置</button></div></header>
   {error&&<div role="alert" className="error-banner"><AlertCircle size={17}/><span>{error}</span><button onClick={()=>setError('')} aria-label="关闭错误"><X size={16}/></button></div>}
   {notice&&<div role="status" className="toast"><Check size={17}/>{notice}</div>}
   {!data?<div className="loading"><LoaderCircle className="spin"/>正在连接你的工作台…<button onClick={()=>refresh().catch(e=>setError(e.message))}>重新连接</button></div>:<>
   {tab==='stories'&&<StoryLibrary/>}
   {tab==='reader'&&!showDemo&&<div className="page"><h1>互动放映室</h1><p>暂无已发布的真实故事视频。请先连接模型，再制作并审核原版。</p><button className="button primary" onClick={()=>setTab('settings')}>连接模型</button></div>}
   {tab==='reader'&&showDemo&&<div className="page reader-page"><div className="page-heading"><div><div className="eyebrow">THE STORY IS YOURS TO CHANGE</div><h1>故事，留一笔给你。</h1><p>随时暂停，写下你的想法。让新的可能，自然走回故事深处。</p></div><button className="button secondary" disabled={busy} onClick={reset}><RotateCcw size={15}/>重新开始</button></div>
    <div className="reader-grid"><section className="screen-column"><div className="film-title"><span className="genre">悬疑</span><h2>{data.story.title}</h2><span className="revision">阅读分支 v{session?.version||1}</span></div>
      <div className="video-shell">{clip&&<video key={`${clip.id}-${entry.start}-${entry.end}`} ref={video} src={clip.media} poster={clip.demo?clip.media.replace('.mp4','.png'):undefined} playsInline preload="auto" onLoadedMetadata={()=>{if(video.current){video.current.currentTime=entry.start;setOffset(entry.start);if(continuePlayback.current){continuePlayback.current=false;video.current.play().catch(()=>setPlaying(false));}}}} onPlay={()=>setPlaying(true)} onPause={()=>{setPlaying(false);getState();}} onSeeked={()=>{if(video.current?.paused)getState();}} onTimeUpdate={()=>{const v=video.current;if(!v)return;setOffset(v.currentTime);if(v.currentTime>=entry.end-.035&&!v.paused){v.pause();if(index<entries.length-1){continuePlayback.current=true;setIndex(index+1);}else setOffset(entry.end);}}} onEnded={()=>{if(index<entries.length-1){continuePlayback.current=true;setIndex(index+1);}}} onError={()=>setError('视频未就绪。请运行初始化脚本生成示意视频，或检查上传文件。')}/>}
       <div className="screen-label"><span className="dot"/> {clip?.demo?'程序示意动画 · 非 AI 成片':'真实素材'}</div>
       {!playing&&<button className="big-play" aria-label="播放视频" onClick={()=>video.current?.play().catch(()=>setError('视频暂时无法播放'))}><Play size={26} fill="currentColor"/></button>}
       <div className="screen-caption"><span>{clip?.title}</span><p>{clip?.events.length?(clip.events.filter(e=>e.at<=offset).at(-1)?.text||(clip.id==='clip_turn'?'陌生人握刀逼近，林夏站在立柱与长椅之间。下一步，还未发生。':clip.id==='clip_end'?'林夏已提交账本，值班室的灯光映着即将到来的黎明。':'新的行动正在展开……')):clip?.narration}</p></div>
      </div>
      <div className="player-controls"><button aria-label={playing?'暂停视频':'播放视频'} onClick={()=>playing?video.current?.pause():video.current?.play()}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><span className="timecode">{time(elapsed)} <span>/ {time(total)}</span></span><input aria-label="当前片段进度" type="range" min={entry?.start||0} max={entry?.end||1} step="0.05" value={Math.min(offset,entry?.end||0)} onChange={e=>{if(video.current){video.current.currentTime=Number(e.target.value);setOffset(Number(e.target.value));}}}/><VolumeX size={16} className="muted"/><button className="edit-at" onClick={pauseForEdit}><Scissors size={15}/>暂停改写</button></div>
      <div className="timeline-label"><span>播放进程</span><span>任意时刻都可以暂停，无需等待选项</span></div><div className="timeline">{entries.map((e,i)=><button key={i} title={data.clips.find(c=>c.id===e.clip_id)?.title} className={`${i===index?'selected ':''}${e.clip_id.startsWith('render')?'branch':''}`} style={{flex:e.end-e.start}} onClick={()=>goTo(i)}><span>{String(i+1).padStart(2,'0')}</span><i/></button>)}</div>
      <div className="under-player"><div><ShieldCheck size={19}/><span><strong>作者主线始终在场</strong><small>保留已发生的事实，让每次改变都有因果。</small></span></div><button className="text-button" onClick={()=>{setPanel(panel==='state'?'rewrite':'state');getState();}}>查看当前状态 <ArrowRight size={14}/></button></div>
      <div className="story-note"><span className="note-index">01 / 作者手记</span><p>“我想写一个普通人没有放弃的夜晚。她可以用不同的方式脱险，但最终，是她亲手把真相带到了天亮。”</p><small>原创示例 · 结局约束：林夏活着提交真实账本</small></div>
    </section>
    <aside className="rewrite-panel"><div className="panel-tabs"><button className={panel==='rewrite'?'selected':''} onClick={()=>setPanel('rewrite')}>改写此刻</button><button className={panel==='history'?'selected':''} onClick={()=>setPanel('history')}>我的足迹 <span>{history.length}</span></button><button className={panel==='state'?'selected':''} onClick={()=>{setPanel('state');getState();}}>状态</button></div>
     {panel==='rewrite'&&<><div className="panel-body"><div className="moment"><span className="orange-dot"/>从 {time(elapsed)} 开始，另一种可能</div><h3>如果是你，会怎样？</h3><p className="helper">改变角色的行动，或写下你希望发生的事。已经发生的故事会被记住。</p><textarea id="rewrite-input" placeholder="例如：林夏侧身躲开，夺下歹徒的刀，退到长椅后面……" value={text} onFocus={()=>video.current?.pause()} onChange={e=>setText(e.target.value)} maxLength={2000}/><div className="input-foot"><span>自然语言改写</span><span>{text.length}/2000</span></div><div className="suggestions"><button onClick={()=>{setText('林夏侧身躲开，夺下歹徒的刀');pauseForEdit();}}>让她夺下刀 <ArrowUpRight size={12}/></button><button onClick={()=>{setText('林夏按下站台紧急按钮呼叫支援');pauseForEdit();}}>尝试求助 <ArrowUpRight size={12}/></button></div>
      <div className="mode-switch"><label>执行方式</label><select aria-label="执行方式" value={mode} onChange={e=>setMode(e.target.value)}><option value="demo">有限演示规则 · 免费</option><option value="live" disabled={!data.settings.llm_configured||!data.settings.paid_enabled}>真实语言模型 · 规划与检查</option></select></div>
      {mode==='demo'&&<label className="checkbox"><input type="checkbox" checked={autoRender} onChange={e=>setAutoRender(e.target.checked)}/>方案通过后，自动制作示意过渡</label>}<button className="button primary wide" disabled={busy||text.trim().length<2||!session||!connected} onClick={rewrite}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>}让故事回应我 <ArrowRight size={16}/></button><p className="fine-print">当前示意视频不模拟真实模型画质。自由改写需配置 API。</p></div>
      {activePlan&&<div className="plan-box"><div className="section-small"><GitBranch size={15}/>过渡方案 <span className="badge">{statusName[activePlan.status]}</span></div>{!plan?<><p>{activePlan.message}</p><div className="progress"><i style={{width:activePlan.progress+'%'}}/></div></>:<><p>{plan.summary}</p>{plan.beats.map((b,i)=><details key={i} className="beat"><summary><span>{i+1}</span>{b.title}<ChevronRight size={13}/></summary><p>{b.narration}</p><small>因果依据：{b.reason}</small></details>)}{plan.suggestions?.map((s,i)=><p className="issue" key={i}>{s}</p>)}{plan.status==='ready'&&<button className="button secondary wide" disabled={busy||!!activeRender||!connected} onClick={render}>{activeRender?<LoaderCircle size={16} className="spin"/>:<Film size={16}/>} {activeRender?activeRender.message:'生成示意过渡并接回主线'}</button>}</> }</div>}
      {plan?.status==='ready'&&data.settings.video_configured&&<div className="plan-box"><div className="section-small"><Film size={15}/>真实视频制作</div><p>此方案包含 {plan.beats.length} 个分镜，各提交一次视频生成。完成后逐镜审核、标注，再接入当前分支。</p><label className="checkbox"><input type="checkbox" checked={paidConfirm} onChange={e=>setPaidConfirm(e.target.checked)}/>确认执行收费调用</label><button className="button primary wide" disabled={!paidConfirm||busy||!connected} onClick={renderLive}>生成真实过渡片段</button></div>}
      {reviewBridge&&<div className="plan-box"><h3>真实过渡等待接入</h3><p>请到原版制作页逐镜检查画面、保存事件时间标注，并通过审核。</p><button className="button secondary wide" onClick={()=>setTab('studio')}>前往片段审核</button><label className="checkbox"><input type="checkbox" checked={bridgeConfirm} onChange={e=>setBridgeConfirm(e.target.checked)}/>已确认首尾人物、服装、道具与位置能够衔接</label><button className="button primary wide" disabled={!bridgeConfirm||busy} onClick={()=>action(async()=>{await api(`/sessions/${session!.id}/commit-bridge`,{version:session!.version,task_id:reviewBridge.id,confirm_visual:bridgeConfirm});await refresh();setNotice('真实过渡已接入，可以继续播放。');})}>将审核过的片段接回主线</button></div>}
      <div className="panel-tip"><span className="tip-star">✳</span><p>改变过程，尊重因果。<br/><small>与固定结局冲突时，会先说明原因。</small></p></div></>}
     {panel==='history'&&<div className="panel-body"><h3>每一次改变，都留下回声。</h3>{history.length===0?<div className="empty"><GitBranch/>还没有改写记录<br/><small>暂停视频，写下第一个不同的选择。</small></div>:history.map(h=><div className="history-card" key={h.id}><small>分支 v{h.revision} · 片段内 {time(h.offset)}</small><p>{h.text}</p></div>)}</div>}
     {panel==='state'&&<div className="panel-body"><h3>这一刻，故事记住了什么</h3><p className="helper">只计算播放到暂停位置的事件。</p>{Object.keys(state).length?Object.entries(state).map(([k,v])=><div className="state-row" key={k}><span>{data.labels[k]||k}</span><strong>{data.values[v]||v}</strong></div>):<button className="button secondary" onClick={()=>getState()}>读取暂停状态</button>}<div className="constraint-note"><ShieldCheck size={17}/><p>{data.story.ending}</p></div></div>}
    </aside></div>
   </div>}

   {tab==='assets'&&<div className="page"><div className="page-heading"><div><div className="eyebrow">A SHARED VISUAL WORLD</div><h1>人物与场景</h1><p>统一的视觉设定，让每一段故事都认得出彼此。</p></div><button className="button primary" onClick={()=>setAssetEdit({name:'',type:'character',description:'',media:''})}><Plus size={17}/>添加素材</button></div><div className="toolbar"><div className="filter-tabs">{[['all','全部素材'],['character','人物'],['scene','场景'],['prop','物品']].map(([id,label])=><button key={id} className={assetFilter===id?'selected':''} onClick={()=>setAssetFilter(id)}>{label}</button>)}</div><div className="search"><Search size={16}/><input placeholder="搜索素材" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="asset-grid">{filteredAssets.map(a=><article className="asset-card" key={a.id}><div className={'asset-art '+a.palette}>{a.media?<img src={a.media} alt={a.name}/>:a.type==='scene'?<img src={a.palette==='amber'?'/media/clip_end.png':'/media/clip_open.png'} alt="场景示意"/>:<div className={'portrait '+(a.palette==='ink'?'dark':'')}><i className="head"/><i className="body"/></div>}<span className="asset-kind">{a.type==='character'?'人物':a.type==='scene'?'场景':'物品'} · {a.media?'已上传':'示意设定'}</span></div><div className="asset-info"><div><h3>{a.name}</h3><span className={'status '+a.status}>{statusName[a.status]}</span></div><p>{a.description}</p><footer><span>{a.parent_id?'修改副本':'共享素材'}</span><button onClick={()=>setAssetEdit(a)}>修改副本 <ArrowUpRight size={14}/></button></footer>{a.status==='pending'&&<div className="review-actions"><button onClick={()=>review(a.id,'approved')}><Check size={14}/>通过</button><button onClick={()=>review(a.id,'rejected')}>退回</button></div>}</div></article>)}</div><div className="info-strip"><ShieldCheck size={18}/>修改会创建独立副本并重新审核。当前版本不自动将新设定应用到已发布故事。</div></div>}

   {tab==='studio'&&<div className="page"><div className="page-heading"><div><div className="eyebrow">THE AUTHOR’S ORIGINAL CUT</div><h1>原版制作</h1><p>从统一设定到已审核片段，为每次改写提供可靠的起点。</p></div><label className="button secondary upload-label"><Upload size={16}/>上传视频<input type="file" accept="video/mp4" hidden onChange={e=>{const f=e.target.files?.[0];if(f)action(async()=>{await upload(f);setNotice('视频已上传，等待审核与时间标注。');});e.target.value='';}}/></label></div>{showDemo&&<div className="studio-intro"><div><span className="tiny-label">作者主线 / ORIGINAL STORY</span><h2>{data.story.title}</h2><p>{data.story.synopsis}</p></div><div className="ending"><ShieldCheck size={21}/><small>作者结局约束</small><strong>{data.story.ending}</strong></div></div>}<div className="section-heading"><h2>片段与审核</h2><span>{visibleClips.length} 个片段</span></div>{visibleClips.length===0&&<p className="empty">尚无真实视频。可在模型连接页生成小样，或上传视频。</p>}<div className="clips-grid">{visibleClips.map((c,i)=><article className="clip-card" key={c.id}><button className="clip-thumb" onClick={()=>setPreview(c)}>{c.demo?<img src={c.media.replace('.mp4','.png')} alt={c.title}/>:<video src={c.media} preload="metadata"/>}<span><Play size={22}/></span><small>{time(c.duration)}</small></button><div className="clip-info"><div><h3>{c.title}</h3><span className={'status '+c.status}>{statusName[c.status]}</span></div><p>{c.demo?'程序示意动画':'真实视频素材'} · {c.events.length} 个时间标注</p><div className="review-actions"><button onClick={()=>setPreview(c)}>预览与标注</button>{c.status!=='approved'&&<button onClick={()=>review(c.id,'approved')}>通过审核</button>}{c.status!=='rejected'&&<button onClick={()=>review(c.id,'rejected')}>退回</button>}</div></div></article>)}</div><div className="info-strip">真实视频审核通过后仍需要核对时间标注；上传不代表自动替换作者原版。</div></div>}

   {tab==='tasks'&&<div className="page"><div className="page-heading"><div><div className="eyebrow">EVERY STEP, REMEMBERED</div><h1>工作流记录</h1><p>每次生成、每次修改，都有可追踪的过程。</p></div><button className="button secondary" disabled={!session||busy} onClick={()=>action(async()=>{await api(`/sessions/${session!.id}/export`,{});await refresh();setNotice('导出任务已加入队列。');})}><Download size={16}/>导出当前示意版</button></div><div className="stat-grid"><div><small>总任务</small><strong>{tasks.length.toString().padStart(2,'0')}</strong></div><div><small>执行与等待</small><strong>{tasks.filter(t=>['queued','running','waiting'].includes(t.status)).length.toString().padStart(2,'0')}</strong></div><div><small>需要处理</small><strong>{tasks.filter(t=>['failed','needs_review'].includes(t.status)).length.toString().padStart(2,'0')}</strong></div><div><small>真实 API 提交</small><strong>{data.settings.paid_used}</strong></div></div><div className="task-list"><div className="task-head"><span>任务</span><span>状态与进度</span><span>执行方式</span><span>操作</span></div>{tasks.length===0?<div className="empty"><Workflow/>还没有任务，试着提交一次剧情改写。</div>:tasks.map(t=><div className="task-row" key={t.id}><div><strong>{{director:'脑洞导演与分镜',image:'真实关键帧生成',plan:'剧情改写与回归',render:'示意过渡制作',video:'真实视频生成',export:'播放列表导出'}[t.kind]||t.kind}</strong><small>{new Date(t.created*1000).toLocaleTimeString('zh-CN')} · {t.id.slice(-8)}</small></div><div><span className={'status '+t.status}>{statusName[t.status]}</span><p>{t.message}</p>{['running','waiting'].includes(t.status)&&<div className="progress"><i style={{width:t.progress+'%'}}/></div>}</div><span className="muted">{t.mode==='live'?'真实 API':'演示 / 本地'}</span><div>{['queued','running','waiting'].includes(t.status)&&<button className="text-button" onClick={()=>action(async()=>{await api(`/tasks/${t.id}/cancel`,{});await refresh();})}>停止</button>}{t.result.media&&<a href={t.result.media} download className="text-button">下载 <Download size={14}/></a>}</div></div>)}</div></div>}

   {tab==='settings'&&<div className="page settings-page"><div className="page-heading"><div><div className="eyebrow">CONNECT YOUR CREATIVE ENGINE</div><h1>模型连接</h1><p>密钥留在本地，创意交给你的模型。</p></div><button className="button secondary" onClick={()=>action(async()=>{await refresh();setNotice('已重新读取本地配置。');})}><RotateCcw size={15}/>重新读取配置</button></div><div className="connection-grid">{[{name:'语言模型',sub:'剧情理解 · 回归规划 · 独立检查',ok:data.settings.llm_configured,model:data.settings.llm_model,icon:Sparkles},{name:'生图模型',sub:'硅基流动 · Z-Image 等文生图模型',ok:data.settings.image_configured,model:data.settings.image_model,icon:Layers3},{name:'视频模型',sub:'MiniMax / 方舟适配器 · 待真实验证',ok:data.settings.video_configured,model:data.settings.video_model,icon:Film}].map(c=><div className="connection-card" key={c.name}><div className="connection-icon"><c.icon size={23}/></div><span className={'status '+(c.ok?'approved':'pending')}>{c.ok?'已配置 · 未代表实测通过':'等待配置'}</span><h3>{c.name}</h3><p>{c.sub}</p><code>{c.model||'尚未填写模型 ID'}</code></div>)}</div><ModelConfig onSaved={refresh}/><ImageWorkflow assets={data.assets} enabled={data.settings.image_configured&&data.settings.paid_enabled} onSaved={refresh}/><div className="video-test"><h2>真实视频小样</h2><p>明确提交一次视频任务，完成后进入原版制作的待审核列表。不会自动替换当前故事。</p><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} aria-label="视频提示词"/><input className="text-input" value={reference} onChange={e=>setReference(e.target.value)} placeholder="参考图 HTTPS 地址（可选，需供应商可读取）"/><label className="checkbox"><input type="checkbox" checked={paidConfirm} onChange={e=>setPaidConfirm(e.target.checked)}/>我确认提交一次真实视频调用，费用由我的供应商账户承担。</label><button className="button primary" disabled={!data.settings.video_configured||!data.settings.paid_enabled||!paidConfirm||busy} onClick={()=>action(async()=>{await api('/video',{prompt,image_url:reference||null,confirm_paid:paidConfirm});await refresh();setNotice('真实视频任务已提交，请到工作流记录查看。');})}><Film size={16}/>生成一个真实小样</button></div></div>}
   {tab==='tasks'&&tasks.some(t=>['failed','needs_review'].includes(t.status)&&t.kind!=='bridge')&&<div className="page recovery-section"><h2>恢复未完成任务</h2><p className="helper">视频只查询已经存在的供应商任务，避免再次收费提交。演示任务可按需恢复，不设次数上限。</p>{tasks.filter(t=>['failed','needs_review'].includes(t.status)&&t.kind!=='bridge').map(t=><div className="recovery-row" key={t.id}><strong>{t.id.slice(-8)}</strong>{t.kind==='video'&&!t.result.provider_id&&<input className="text-input" placeholder="在供应商控制台核实后，填写已有任务编号" value={recovery[t.id]||''} onChange={e=>setRecovery({...recovery,[t.id]:e.target.value})}/>}<button className="button secondary" disabled={busy||(t.kind==='video'&&!t.result.provider_id&&!recovery[t.id])} onClick={()=>action(async()=>{await api(`/tasks/${t.id}/resume`,recovery[t.id]?{provider_id:recovery[t.id]}:{});await refresh();})}>恢复已有任务</button></div>)}</div>}
   </>}
   <footer className="page-footer"><span>叙间 STORYLOOM</span><span>让故事拥有另一种可能。</span><span>本地原型 · 不对外公开</span></footer>
  </main>
  {assetEdit&&<div className="modal-backdrop" onClick={()=>setAssetEdit(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-title"><h2>{assetEdit.id?'修改素材副本':'添加新素材'}</h2><button onClick={()=>setAssetEdit(null)} aria-label="关闭"><X size={20}/></button></div><p className="helper">保存为独立副本，审核后可在制作时选用。</p><label>名称<input className="text-input" value={assetEdit.name||''} onChange={e=>setAssetEdit({...assetEdit,name:e.target.value})}/></label><label>类型<select className="text-input" value={assetEdit.type} onChange={e=>setAssetEdit({...assetEdit,type:e.target.value})}><option value="character">人物</option><option value="scene">场景</option><option value="prop">物品</option></select></label><label>具体设定<textarea value={assetEdit.description||''} onChange={e=>setAssetEdit({...assetEdit,description:e.target.value})}/></label><label className="button secondary upload-label"><Upload size={15}/>{uploadBusy?'上传中…':assetEdit.media?'替换参考图':'上传参考图'}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setUploadBusy(true);try{const url=await upload(f);setAssetEdit(x=>x?{...x,media:url}:x);}catch(e){setError((e as Error).message);}finally{setUploadBusy(false);}}}/></label>{assetEdit.media&&<img className="upload-preview" src={assetEdit.media} alt="参考图预览"/>}<button className="button primary wide" disabled={busy||uploadBusy||!assetEdit.name||!assetEdit.description} onClick={saveAsset}>保存并提交审核</button></div></div>}
  {preview&&<div className="modal-backdrop" onClick={()=>setPreview(null)}><div className="modal wide-modal" onClick={e=>e.stopPropagation()}><div className="modal-title"><h2>{preview.title}</h2><button onClick={()=>setPreview(null)} aria-label="关闭"><X size={20}/></button></div><video src={preview.media} controls/><p>{preview.narration}</p><h3>事件发生的时间</h3><p className="helper">播放后核对每个事件实际完成的时刻。生成任务提供的时间只是待核对建议，保存后还需通过审核。</p>{annotation.map((ev,i)=><div className="annotation-row" key={i}><label>发生于（秒）<input className="text-input" type="number" min="0" max={preview.duration} step="0.1" disabled={preview.id.startsWith('clip_')} value={ev.at} onChange={e=>setAnnotation(annotation.map((x,j)=>j===i?{...x,at:Number(e.target.value)}:x))}/></label><div><p>{ev.text}</p><small>{Object.entries(ev.changes).map(([k,v])=>`${data?.labels[k]||k} → ${data?.values[v]||v}`).join('；')}</small></div></div>)}{annotation.length===0&&<p className="helper">此视频没有结构化事件草稿。当前可审核和预览，但不能自动作为剧情过渡使用。</p>}{!preview.id.startsWith('clip_')&&annotation.length>0&&<button className="button secondary" disabled={busy} onClick={()=>action(async()=>{const c=await api<Clip>(`/clips/${preview.id}/annotate`,{events:annotation});setPreview(c);await refresh();setNotice('时间标注已保存，请确认画面后通过审核。');})}>保存时间标注</button>}<div className="review-actions"><button disabled={busy} onClick={()=>review(preview.id,'approved')}><Check size={15}/>通过审核</button>{!preview.id.startsWith('clip_')&&<button disabled={busy} onClick={()=>review(preview.id,'rejected')}>退回修改</button>}</div></div></div>}
 </div>;
}
