'use client';
import ProductionHarness from './ProductionHarness';
import Preproduction from './Preproduction';
import CreativeStudio from './CreativeStudio';
import {useEffect,useState} from 'react';
type Shot={id:string,purpose:string,edit_seconds:number,generation_seconds:number,setup_ids:string[],assets:string[],[key:string]:string|number|string[]};
type Board={title:string,scope_note:string,shots:Shot[]};
type Project={board_diagnostics?:{errors:{field:string,reason:string}[]},archived?:boolean,archive_note?:string,restart_of?:string,id:string,version:number,status:string,brief:string,board?:Board,treatment?:{premise:string,dramatic_question:string,protagonist_goal:string,excerpt_scope:string,visual_strategy:string,information_strategy:string,boundaries:string[],rules:{rule:string,quote:string,consequence:string}[]},review?:{approved:boolean,issues:string[],continuity?:string,dramatic_logic?:string,editability?:string,production_feasibility?:string},events?:{at:number,message:string}[],task?:{status:string,message:string,progress:number,created:number}};
const fields:Record<string,string>={scene:'场次 / 内外景 / 时间',source_quote:'原文依据',dramatic_action:'叙事动作',size:'景别',camera:'机位、焦段倾向与运镜',composition:'构图与视觉重点',blocking:'走位、视线与轴线',continuity_in:'入镜状态',continuity_out:'出镜状态',viewer_knows:'观众已知',character_knows:'人物已知',withhold:'暂不揭示',dialogue:'对白 / 旁白',sound:'环境声、音效与音乐',transition:'剪辑与声音衔接',reference_prompt:'镜头参考图设计',motion_prompt:'单镜运动指令',generation_risk:'生成风险与替代拍法'};
const purposes:Record<string,string>={hook:'钩子',setup:'铺垫',rule:'规则展示',escalation:'升级',reveal:'揭示',reaction:'反应',payoff:'回收',bridge:'衔接'};
async function api<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/director'+path,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'请求格式不正确');return d;}
export default function BrainstormDirector({sourceId}:{sourceId:string}){
 const [projects,setProjects]=useState<Project[]>([]),[brief,setBrief]=useState('制作原文内一个完整短场景，突出脑洞规则与人物反应。'),[paid,setPaid]=useState(false),[confirmed,setConfirmed]=useState(false),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[draft,setDraft]=useState<Board|null>(null),[editVersion,setEditVersion]=useState(0);
 const [selected,setSelected]=useState(''),[restart,setRestart]=useState(''),[archiveNote,setArchiveNote]=useState(''),[history,setHistory]=useState<Record<string,{media:{id:string,media:string,name?:string,title?:string}[]}>>({});
 const activeProjects=projects.filter(p=>!p.archived);
 const project=activeProjects.find(p=>p.id===selected)||activeProjects[0];
 const [expert,setExpert]=useState(false);
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
 async function refresh(){setProjects(await api<Project[]>('/'+sourceId));}
 useEffect(()=>{let alive=true;const load=()=>api<Project[]>('/'+sourceId).then(x=>{if(alive)setProjects(x);}).catch(e=>{if(alive)setMessage(e.message);});load();const t=setInterval(load,3000);return()=>{alive=false;clearInterval(t);};},[sourceId]);
 async function act(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const running=project?.task&&['queued','running','waiting'].includes(project.task.status);
 return <section className="config-guide" style={{marginTop:24}}><h2>脑洞漫剧 · 制作工作台</h2><p>先理解原著，再选择风格、审核图片，最后由系统完成视频制作。当前先改编原文中的一个短场景。</p>
 <div className="harness-notice"><h3>方案管理</h3>{activeProjects.length>0&&<label>当前方案<select value={project?.id||''} disabled={busy||!!draft} onChange={e=>{setSelected(e.target.value);setConfirmed(false);setNote('');}}>{activeProjects.map(p=><option key={p.id} value={p.id}>{p.board?.title||'导演草案'} · {p.id.slice(-8)}</option>)}</select></label>}
 {project&&<><input aria-label="归档原因" placeholder="归档原因（可选，例如画风不统一，重新设计）" value={archiveNote} onChange={e=>setArchiveNote(e.target.value)}/><button className="button secondary" disabled={busy||!!draft} onClick={()=>act(async()=>{await api('/projects/'+project.id+'/archive',{version:project.version,archived:true,note:archiveNote});setSelected('');setConfirmed(false);setNote('');setMessage('已归档，历史素材与费用记录保留。可在归档列表准备重做。');})}>归档当前废案</button></>}
 <details><summary>已归档方案（{projects.filter(p=>p.archived).length}）</summary>{projects.filter(p=>p.archived).map(p=><article key={p.id} style={{padding:16,borderBottom:'1px solid #ddd'}}><h4>{p.board?.title||'未完成导演草案'} · {p.id.slice(-8)}</h4><p>{p.archive_note||'未填写归档原因'}</p><p>{p.brief}</p><details><summary>查看旧导演与分镜</summary><p>{p.treatment?.premise}</p>{p.board?.shots.map(s=><p key={s.id}><b>{s.id}</b> {s.dramatic_action}</p>)}</details><button className="button secondary" disabled={busy} onClick={()=>act(async()=>{const h=await api<{media:{id:string,media:string,name?:string,title?:string}[]}>('/projects/'+p.id+'/history');setHistory({...history,[p.id]:h});})}>查看历史素材</button><button className="button secondary" disabled={busy||!!draft} onClick={()=>{setRestart(p.id);setBrief(p.brief);setPaid(false);setMessage('已准备重做：修改下方创作要求，确认收费后点击生成。旧方案不会被覆盖。');}}>基于原故事准备重做</button><button className="button secondary" disabled={busy||!!draft} onClick={()=>act(async()=>{await api('/projects/'+p.id+'/archive',{version:p.version,archived:false,note:'恢复归档方案'});setSelected(p.id);setMessage('已恢复。视觉绑定需按当前版本重新审核。');})}>恢复方案</button>{history[p.id]?.media.map(m=><div key={m.id}><a href={m.media} target="_blank" rel="noreferrer">{m.name||m.title||m.id}</a></div>)}</article>)}</details>
 {restart&&<p>正在准备归档方案 {restart.slice(-8)} 的新一轮制作。<button onClick={()=>setRestart('')}>取消重做准备</button></p>}<p>归档不删除素材、不撤回已发布作品，也不退还供应商费用。归档和准备重做本身不调用模型。</p></div>
 <details><summary>改编补充要求（可选）</summary><label>补充要求<textarea style={{display:'block',width:'100%',minHeight:90}} value={brief} onChange={e=>setBrief(e.target.value)}/></label></details>
 <label className="checkbox"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/>确认本次导演阐述调用语言模型 1 次；选角搭景审核后另行生成分镜</label><button className="button primary" disabled={!paid||busy||!!running||!!draft} onClick={()=>act(async()=>{const created=await api<{project_id:string}>('',{source_id:sourceId,brief,confirm_paid:true,restart_of:restart||null});setSelected(created.project_id);setRestart('');setConfirmed(false);setNote('');})}>生成导演阐述，开始前期准备</button>
 {message&&<p role="status">{message}</p>}{project?.task&&<p>{project.task.message} · {project.task.progress}%</p>}
 {project?.board_diagnostics&&<div role="alert" className="harness-notice"><h3>分镜格式诊断（尚未进入剧情预审）</h3><p>shots.0 表示第 1 镜，以此类推。原始返回已保存，未自动重新调用模型。</p>{project.board_diagnostics.errors.map((e,i)=><p key={i}><b>{e.field}</b>：{e.reason}</p>)}</div>}
 {project&&<div className="director-run"><div className="run-stage-row">{['导演阐述','选角与搭影棚','定装试拍','正式分镜与预审','影像制作'].map((label,i)=><div key={label} className={i===0&&running&&!project.treatment||i===1&&!running&&project.status==='awaiting_preproduction'||i===3&&running&&project.treatment?'active':''}><span>0{i+1}</span>{label}</div>)}</div><h3 aria-live="polite">{running?<><i className="run-pulse"/>{project.task?.message}</>:project.status==='approved'?'分镜已批准 · 在下方开始影像制作':project.board?'分镜已就绪 · 请展开审核区，确认后开始制作':project.task?.message}</h3>{running&&<p>已等待 {Math.floor((now-(project.task?.created||now/1000)*1000)/1000)} 秒 · 模型生成期间会持续等待响应，不表示卡住</p>}<div className="run-event-list">{project.events?.map((e,i)=><p key={i}><time>{new Date(e.at*1000).toLocaleTimeString('zh-CN')}</time>{e.message}</p>)}</div><p>当前主操作：{running?'等待本阶段完成，结果会自动显示':project.status==='approved'?'确认选角搭景版本 → 三镜小样 → 批量镜头参考图 → 视频审片 → 发布':project.board?'审核分镜，再开启影像制作':project.status==='awaiting_preproduction'?'完成下方选角、影棚与试拍审核':'处理任务提示后重新提交'}</p>{project.board&&project.status!=='approved'&&!running&&<a className="button primary" href="#board-review">前往分镜审核 ↓</a>}</div>}
 {project?.treatment&&<CreativeStudio key={'creative'+project.id} projectId={project.id}/>}
 <button className="button secondary" onClick={()=>setExpert(!expert)}>{expert?'收起高级制作详情':'高级制作详情（可选）'}</button>
 {expert&&project?.treatment&&<Preproduction key={project.id} projectId={project.id} version={project.version} running={!!running} onRefresh={refresh}/>}
 {expert&&project?.board&&project.status==='approved'&&<ProductionHarness key={project.id} projectId={project.id}/>}
 {project?.treatment&&<><details className="artifact-details"><summary>导演阐述 · 查看已生成产物</summary><p><b>核心脑洞：</b>{project.treatment.premise}</p><p><b>戏剧问题：</b>{project.treatment.dramatic_question}</p><p><b>人物目标：</b>{project.treatment.protagonist_goal}</p><p><b>本场范围：</b>{project.treatment.excerpt_scope}</p><p><b>视觉策略：</b>{project.treatment.visual_strategy}</p><p><b>信息策略：</b>{project.treatment.information_strategy}</p>{project.treatment.rules.map((r,i)=><blockquote key={i}><b>{r.rule}</b><p>原文：“{r.quote}”</p><p>后果：{r.consequence}</p></blockquote>)}<p>边界：{project.treatment.boundaries.join('；')}</p></details></>}
 {expert&&project?.board&&<details id="board-review" className="artifact-details" open={!running&&project.status!=='approved'}><summary>分镜审核 · 查看、修改并批准</summary><h3>{project.board.title}</h3><p>{project.board.scope_note}</p><p>成片计划 {(draft||project.board).shots.reduce((n,s)=>n+s.edit_seconds,0)} 秒 · 生成素材 {(draft||project.board).shots.reduce((n,s)=>n+s.generation_seconds,0)} 秒 · 不含声音后期时间</p>
 {!draft?<button className="button secondary" disabled={!!running||busy} onClick={()=>{setDraft(structuredClone(project.board!));setEditVersion(project.version);}}>修改分镜内容</button>:<><button className="button primary" disabled={busy} onClick={()=>act(async()=>{await api('/projects/'+project.id+'/edit',{version:editVersion,board:draft});setDraft(null);setConfirmed(false);})}>保存修改并重新审核</button><button className="button secondary" onClick={()=>setDraft(null)}>取消修改</button></>}
 {(draft||project.board).shots.map((s,i)=><article className="clip-card" style={{padding:20,marginTop:18}} key={s.id}><h3>{s.id} · {purposes[s.purpose]} · {s.size}</h3><p>剪辑 {s.edit_seconds}s / 生成 {s.generation_seconds}s · 铺垫引用：{s.setup_ids.join('、')||'无'} · 资产：{s.assets.join('、')}</p><details><summary>镜头设计参数与依据</summary>{Object.entries(fields).map(([key,label])=><div key={key} style={{margin:'10px 0'}}><b>{label}</b>{draft?<textarea aria-label={s.id+' '+label} style={{display:'block',width:'100%',minHeight:60}} value={String(s[key]??(key==='reference_prompt'?s.first_frame:'')??'')} onChange={e=>setDraft({...draft,shots:draft.shots.map((shot,j)=>j===i?{...shot,[key]:e.target.value}:shot)})}/>:<p style={{whiteSpace:'pre-wrap'}}>{String(s[key]||(key==='reference_prompt'?s.first_frame:'')||'无')}</p>}</div>)}</details>{project.status==='approved'&&!draft&&<button className="button secondary" disabled={busy||!paid} onClick={()=>act(async()=>{await api('/projects/'+project.id+'/shots/'+s.id+'/image',{version:project.version,confirm_paid:true});setMessage('该镜镜头参考图任务已提交，完成后在模型连接页查看、审核并生成视频。');})}>生成该镜镜头参考图（收费 1 次）</button>}</article>)}
 <h3>文本预审与人工审核</h3><p>{project.review?.approved?'模型文本预审通过，仍需人工逐镜审核':'预审未通过或尚未完成，请检查问题'}</p>{project.review?.issues?.map((x,i)=><p key={i}>{x}</p>)}{project.review&&<div className="harness-notice">{(['continuity','dramatic_logic','editability','production_feasibility'] as const).map(k=>project.review?.[k]&&<p key={k}><b>{{continuity:'连续性',dramatic_logic:'叙事因果',editability:'剪辑可用性',production_feasibility:'制作可行性'}[k]}：</b>{project.review[k]}</p>)}</div>}<p>人工复核：规则与原文一致、铺垫先于揭示、人物因果、视线轴线与道具连续、对白可说完、镜头有剪辑余量。模型预审不等于成片验收。</p>
 <label className="checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已逐镜核对，并处理预审问题</label><textarea aria-label="分镜审核说明" placeholder="记录审核结论或问题处理说明（至少 5 字）" value={note} onChange={e=>setNote(e.target.value)}/><button className="button primary" disabled={busy||!!running||!!draft||!confirmed||note.trim().length<5||project.status==='approved'} onClick={()=>act(async()=>{await api('/projects/'+project.id+'/approve',{version:project.version,confirm:confirmed,note});})}>{project.status==='approved'?'当前分镜已批准':'批准分镜进入镜头参考图制作'}</button></details>}
 </section>;
}
