'use client';
import {useEffect,useState} from 'react';
type Spec={role:'character'|'scene'|'prop',name:string,notes:string};
type Asset={id:string,name:string,media:string,status:string};
type Trial={task:{id:string,status:string,message:string},asset:Asset|null};
type Data={config:{version:number,style:string,assets:Record<string,Spec>}|null,previous_config?:{style:string,assets:Record<string,Spec>}|null,stamp:string,approved:boolean,reason:string,assets:Asset[],trials:Trial[]};
export default function Preproduction({projectId,version,running,onRefresh}:{projectId:string,version:number,running:boolean,onRefresh:()=>Promise<void>}){
 const [data,setData]=useState<Data|null>(null),[style,setStyle]=useState(''),[assets,setAssets]=useState<Record<string,Spec>>({}),[refs,setRefs]=useState<string[]>([]),[trialPrompt,setTrialPrompt]=useState('演员站在影棚中，展示全身服装、身材比例和门窗位置，保持统一画风。'),[selected,setSelected]=useState<string[]>([]),[note,setNote]=useState(''),[paid,setPaid]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const base='/api/preproduction/'+projectId;
 async function request(path:string,body?:unknown){const r=await fetch(path,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'请补全设定字段');return d;}
 async function refresh(){setData(await request(base));}
 useEffect(()=>{let alive=true;request(base).then(d=>{if(!alive)return;setData(d);if(d.config){setStyle(d.config.style);setAssets(d.config.assets);}}).catch(e=>setMessage(e.message));const t=setInterval(()=>request(base).then(d=>{if(alive)setData(d);}).catch(()=>{}),3000);return()=>{alive=false;clearInterval(t);};},[base]);
 async function act(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await refresh();await onRefresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!data)return <p>正在准备选角与影棚…</p>;
 return <section className="visual-setup"><h2>选角与搭影棚 · 分镜前置准备</h2><p>导演阐述决定拍什么；先确定演员和空间，再决定如何拍。参考图在“人物与场景”中创建、上传和审核。</p>{data.previous_config&&<button className="button secondary" onClick={()=>{setStyle(data.previous_config!.style);setAssets(data.previous_config!.assets);setMessage('已载入旧案的演员与影棚设定。请核对资产后保存并重新确认试拍。');}}>沿用归档旧案的演员与影棚设定</button>}
 <label>统一美术风格<textarea value={style} onChange={e=>setStyle(e.target.value)} placeholder="画风、色彩、材质、服装时代与光线基调（至少10字）"/></label><h3>① 选角 · ② 搭影棚</h3><p>角色说明写明年龄感、发型、体型、服装及允许状态；影棚说明写明门窗、光源、活动区域、空间连接及道具位置。</p>
 <div className="reference-gallery">{data.assets.map(a=><figure key={a.id}><img src={a.media} alt={a.name}/><label><input type="checkbox" checked={!!assets[a.id]} onChange={e=>{const next={...assets};if(e.target.checked)next[a.id]={role:'character',name:a.name,notes:''};else delete next[a.id];setAssets(next);}}/>{a.name}</label></figure>)}</div>
 {Object.entries(assets).map(([id,s])=><div key={id}><label>{s.name}<select aria-label={s.name+' 类型'} value={s.role} onChange={e=>setAssets({...assets,[id]:{...s,role:e.target.value as Spec['role']}})}><option value="character">演员／角色</option><option value="scene">影棚／场景</option><option value="prop">道具</option></select></label><input aria-label={s.name+' 剧中名称'} value={s.name} onChange={e=>setAssets({...assets,[id]:{...s,name:e.target.value}})}/><textarea aria-label={s.name+' 设定说明'} value={s.notes} onChange={e=>setAssets({...assets,[id]:{...s,notes:e.target.value}})}/></div>)}
 <button className="button secondary" disabled={busy||running} onClick={()=>act(async()=>{await request(base,{expected_version:data.config?.version||0,style,assets});setConfirmed(false);setSelected([]);setMessage('选角与影棚已保存，下一步制作定装试拍。');})}>保存选角与影棚</button>
 <h3>③ 定装与试拍</h3><p>每次选择2–3张已保存参考图，包含演员和场景。可分组试拍，审核结果须覆盖全部资产。采用项目内固定的 Qwen 参考合成模型，沿用已配置的硅基流动账户。</p>{Object.entries(data.config?.assets||{}).map(([id,s])=><label className="checkbox" key={id}><input type="checkbox" checked={refs.includes(id)} onChange={e=>setRefs(e.target.checked?[...refs,id]:refs.filter(x=>x!==id))}/>{s.name} · {{character:'演员',scene:'影棚',prop:'道具'}[s.role]}</label>)}<textarea aria-label="定装试拍要求" value={trialPrompt} onChange={e=>setTrialPrompt(e.target.value)}/><label className="checkbox"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/>确认本次点击的模型调用费用</label><button className="button secondary" disabled={busy||running||!paid||refs.length<2||refs.length>3||!data.stamp} onClick={()=>act(async()=>{await request(base+'/trial',{stamp:data.stamp,assets:refs,prompt:trialPrompt,confirm_paid:true});})}>生成定装试拍图</button>
 <div className="production-grid">{data.trials.map(t=><article className="production-shot" key={t.task.id}><p>{t.task.message||t.task.status}</p>{t.asset&&<><img style={{width:'100%',maxHeight:350,objectFit:'contain'}} src={t.asset.media} alt="演员与影棚试拍"/><button disabled={busy} onClick={()=>act(async()=>{await request('/api/review/'+t.asset!.id,{status:'approved',note:'已核对定装与场景画风、比例、布局'});})}>审核此试拍图</button><button disabled={busy} onClick={()=>act(async()=>{await request('/api/review/'+t.asset!.id,{status:'rejected',note:'定装试拍不符合选角或搭景要求'});})}>退回试拍图</button>{t.asset.status==='approved'&&<label className="checkbox"><input type="checkbox" checked={selected.includes(t.asset.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.asset!.id]:selected.filter(x=>x!==t.asset!.id))}/>纳入本轮试拍审核</label>}</>}</article>)}</div>
 <textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="试拍审核结论：人物、服装、比例、空间、画风（至少10字）"/><label className="checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已确认选角、搭景与试拍结果，可进入正式分镜</label><button className="button primary" disabled={busy||running||!confirmed||note.trim().length<10||!selected.length} onClick={()=>act(async()=>{await request(base+'/approve',{stamp:data.stamp,asset_ids:selected,note,confirm:true});setMessage('前期准备已审核。');})}>批准选角、影棚与试拍</button>
 <h3>④ 正式分镜</h3><p>{data.reason}</p><button className="button primary" disabled={busy||running||!paid||!data.approved} onClick={()=>act(async()=>{await request('/api/director/projects/'+projectId+'/storyboard',{version,confirm_paid:true});setMessage('正在基于已审核演员和影棚生成分镜，并进行独立检查。');})}>生成／重做正式分镜（收费）</button>{message&&<p role="status">{message}</p>}</section>;
}
