'use client';
import {useEffect,useState} from 'react';
import VisualConsistency,{VisualStatus} from './VisualConsistency';
type Job={status:string,message:string,progress:number};
type StoredSelection={start:number,end:number,boundaries:{first:{media:string},last:{media:string}}};
type ShotRun={shot:{id:string,dramatic_action:string,edit_seconds:number},image_task:Job|null,video_task:Job|null,asset:{id:string,media:string,status:string}|null,clip:{id:string,media:string,duration:number,visual_reviewed?:boolean,locked?:boolean,reader_trim?:{start:number,end:number}}|null,storage?:{schema_version:number,artifact:unknown,selected_use:StoredSelection|null}|null};
const stopped=(job:Job|null)=>!!job&&['failed','needs_review','cancelled','superseded'].includes(job.status);
const imageState=(job:Job|null)=>!job?'等待开始':stopped(job)?'生图已停止':job.status==='queued'?'镜头参考图排队中':job.status==='waiting'?'等待供应商':job.status==='completed'?'正在读取素材':'正在制作镜头参考图';
type Run={approved:boolean,version:number,shots:ShotRun[]};
async function request(path:string,body?:unknown){const r=await fetch('/api'+path,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'操作未完成');return d;}
export default function ProductionHarness({projectId}:{projectId:string}){
 const [run,setRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[paid,setPaid]=useState(false),[message,setMessage]=useState(''),[cuts,setCuts]=useState<Record<string,{start:number,end:number}>>({});
 const [visual,setVisual]=useState<VisualStatus>({approved:false,samples:[],passed:false});
 const base='/production/'+projectId;
 async function refresh(){setRun(await request(base));}
 useEffect(()=>{let active=true;const load=()=>request(base).then(d=>{if(active)setRun(d);}).catch(e=>{if(active)setMessage(e.message);});load();const t=setInterval(load,2500);return()=>{active=false;clearInterval(t);};},[base]);
 async function act(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!run)return <p>正在连接制作执行器…</p>;
 const completed=run.shots.filter(s=>s.clip?.visual_reviewed).length;
 return <section className="harness"><header><div><span className="eyebrow">PRODUCTION RUN</span><h2>让分镜成为可看的故事</h2><p>{completed} / {run.shots.length} 镜已审片 · 产物逐步出现，无需前往模型设置页</p></div><span className="run-pill">{!run.approved?'等待分镜批准':!visual.approved?'等待视觉设定审核':!visual.passed?'三镜小样阶段':'批量制作已解锁'}</span></header>
 {!run.approved&&<p className="harness-notice">先在“分镜审核”中确认方案。文字生成成功后不会绕过审核直接产生图片或视频费用。</p>}
 <VisualConsistency projectId={projectId} version={run.version} shots={run.shots.map(s=>s.shot)} onStatus={setVisual}/>
 <label className="checkbox"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/>允许本次点击的图片／视频生成操作收费</label>
 <div className="harness-actions"><button className="button primary" disabled={!visual.passed||!run.approved||!paid||busy} onClick={()=>act(async()=>{for(const s of run.shots){if(!s.image_task)await request('/director/projects/'+projectId+'/shots/'+s.shot.id+'/image',{version:run.version,confirm_paid:true});}setMessage('尚未开始的镜头参考图已排队。图片出现后，请直接在卡片中审核。');})}>生成缺少的镜头参考图</button><button className="button secondary" disabled={!visual.passed||!paid||busy||!run.approved||!run.shots.some(s=>s.asset?.status==='approved'&&!s.video_task)} onClick={()=>act(async()=>{for(const s of run.shots){if(s.asset?.status==='approved'&&!s.video_task)await request(base+'/shots/'+s.shot.id+'/video',{version:run.version,confirm_paid:true});}setMessage('已审核图片对应的视频已排队。');})}>将已审镜头参考图送入视频生成</button></div>
 {message&&<p role="status" className="harness-notice">{message}</p>}
 <div className="production-grid">{run.shots.map(s=>{const cut=cuts[s.shot.id]||s.clip?.reader_trim||{start:0,end:Math.min(s.shot.edit_seconds,s.clip?.duration||s.shot.edit_seconds)};return <article className="production-shot" key={s.shot.id}><h3>{s.shot.id} <small>{s.clip?.visual_reviewed?'已审片':s.video_task?(stopped(s.video_task)?'视频已停止':'视频制作'):s.asset?'等待图片审核':imageState(s.image_task)}</small></h3><p>{s.shot.dramatic_action}</p>
 <div className="production-preview">{s.clip?<video src={s.clip.media} controls preload="metadata"/>:s.asset?<img src={s.asset.media} alt={s.shot.id+' 镜头参考图'}/>:<div className={s.image_task?.status==='running'?'working-placeholder':'working-placeholder idle'}>{s.image_task?imageState(s.image_task):'镜头参考图将在这里出现'}</div>}</div>
 {s.image_task&&<p className="run-message">图片：{s.image_task.message}</p>}{s.video_task&&<p className="run-message">视频：{s.video_task.message}</p>}
 {s.clip&&<p className="run-message">{s.storage?.artifact?'已保存为独立片段，可在不同剧情中引用。':'现有片段可继续播放；审片时将补齐存储信息。'}</p>}
 {s.storage?.selected_use&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>{([['first','选区入画'],['last','选区出画']] as const).map(([key,label])=><figure key={key} style={{margin:0}}><img src={s.storage!.selected_use!.boundaries[key].media} alt={s.shot.id+' '+label} loading="lazy" style={{width:'100%',display:'block',borderRadius:8}}/><figcaption>{label}</figcaption></figure>)}</div>}
 {s.image_task?.message.includes('HTTP 402')&&<p role="alert" className="harness-notice">硅基流动拒绝了付款请求（HTTP 402），通常是账户可用余额不足。请核对生图 Key 所属账号的余额与付费权限，处理后先重试一镜。本地次数限制已取消，不影响供应商收费。</p>}
 <div className="harness-actions">{!s.asset&&<button className="button secondary" disabled={!visual.approved||(!visual.passed&&!visual.samples.includes(s.shot.id))||busy||!paid||!run.approved||!!s.image_task&&['queued','running','waiting','completed'].includes(s.image_task.status)} onClick={()=>act(async()=>{await request('/director/projects/'+projectId+'/shots/'+s.shot.id+'/image',{version:run.version,confirm_paid:true});})}>{s.image_task?'重新提交生图（收费）':'生成镜头参考图'}</button>}
 {s.asset&&<><button className="button secondary" disabled={busy} onClick={()=>act(async()=>{await request('/review/'+s.asset!.id,{status:'rejected',note:'人物、场景或画风不一致，需重做'});})}>退回：一致性不通过</button><button className="button secondary" disabled={busy||!paid||!visual.approved||(!visual.passed&&!visual.samples.includes(s.shot.id))} onClick={()=>act(async()=>{await request('/director/projects/'+projectId+'/shots/'+s.shot.id+'/image',{version:run.version,confirm_paid:true,remake:true});})}>重做此镜（收费）</button></>}
 {s.asset&&s.asset.status!=='approved'&&<button className="button primary" disabled={busy} onClick={()=>act(async()=>{await request('/review/'+s.asset!.id,{status:'approved',note:'制作工作台已查看并确认镜头参考图'});})}>确认镜头参考图可用</button>}
 {s.asset?.status==='approved'&&!s.clip&&<button className="button primary" disabled={!visual.passed||busy||!paid||!!s.video_task&&['queued','running','waiting','completed'].includes(s.video_task.status)} onClick={()=>act(async()=>{await request(base+'/shots/'+s.shot.id+'/video',{version:run.version,confirm_paid:true});})}>{s.video_task?'重新提交视频（收费）':'生成该镜视频'}</button>}</div>
 {s.clip&&<div className="cut-controls"><p>观看成片，选取要呈现给读者的区间（秒）。保存时对齐实际视频帧。</p><label>开始<input type="number" min={0} max={s.clip.duration} step="any" value={cut.start} disabled={s.clip.locked} onChange={e=>setCuts({...cuts,[s.shot.id]:{...cut,start:Number(e.target.value)}})}/></label><label>结束<input type="number" min={0} max={s.clip.duration} step="any" value={cut.end} disabled={s.clip.locked} onChange={e=>setCuts({...cuts,[s.shot.id]:{...cut,end:Number(e.target.value)}})}/></label><button className="button secondary" disabled={busy||s.clip.locked} onClick={()=>act(async()=>{const saved=await request(base+'/shots/'+s.shot.id+'/approve-clip',{version:run.version,...cut,confirm_visual:true});setCuts(previous=>({...previous,[s.shot.id]:saved.reader_trim}));})}>{s.clip.visual_reviewed?'更新审片区间':'确认画面与区间'}</button></div>}
 </article>;})}</div>
 <footer className="publish-bar"><div><h3>交给读者的，是故事。</h3><p>全部镜头审片后，按分镜顺序组成短片，放入本地读者空间。</p></div><button className="button primary" disabled={!visual.passed||busy||completed!==run.shots.length||!completed} onClick={()=>act(async()=>{await request(base+'/publish',{version:run.version,confirm:true});setMessage('已发布。读者端会展示该作品，管理台保持独立。');})}>放入读者空间</button></footer>
 </section>;
}
