'use client';
import {useEffect,useState} from 'react';
type Asset={id:string,name:string,media:string,status:string,director_id?:string};
export type VisualStatus={approved:boolean,samples:string[],passed:boolean};
export default function VisualConsistency({projectId,version,shots,onStatus}:{projectId:string,version:number,shots:{id:string,dramatic_action:string}[],onStatus:(v:VisualStatus)=>void}){
 const [data,setData]=useState<any>(null),[style,setStyle]=useState(''),[bindings,setBindings]=useState<Record<string,string[]>>({}),[states,setStates]=useState<Record<string,string>>({}),[samples,setSamples]=useState<string[]>([]),[confirmed,setConfirmed]=useState(false),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const base='/api/consistency/'+projectId;
 async function read(){const r=await fetch(base);if(!r.ok)throw Error('视觉设定读取失败');return r.json();}
 useEffect(()=>{let alive=true;read().then(d=>{if(!alive)return;setData(d);const c=d.config||d.defaults;if(c){setStyle(c.style);setBindings(c.bindings);setStates(c.states);setSamples(c.samples);setConfirmed(c.approved);}else{setSamples(shots.slice(0,3).map(s=>s.id));setStates(Object.fromEntries(shots.map(s=>[s.id,''])));} });const t=setInterval(()=>read().then(d=>{if(alive)setData(d);}).catch(()=>{}),2500);return()=>{alive=false;clearInterval(t);};},[base]);
 useEffect(()=>{onStatus({approved:!!data?.config?.approved&&data.config.director_version===version,samples:data?.config?.samples||[],passed:!!data?.sample_passed});},[data,version]);
 async function send(path:string,body:unknown){setBusy(true);try{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'请补全所有设定');setData(await read());setMessage('已保存审核结果');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!data)return <p>正在读取视觉规范…</p>;
 const assets:Asset[]=data.assets;
 return <section className="visual-setup"><h3>① 核对分镜参考与连续性</h3><p>新流程自动继承已审核的选角、影棚与统一画风。逐镜核对绑定及连续性状态，再选择三镜小样；若需改换演员或搭景，请返回前期准备。</p><p>参考生图使用 Qwen/Qwen-Image-Edit-2509，沿用硅基流动 Key，按该模型单独计费。原有 Z-Image 可继续用于设定图探索。</p><label>统一画风、人物外观与场景规则<textarea readOnly={!!data.defaults} value={style} onChange={e=>setStyle(e.target.value)} placeholder="例如统一二维漫画画风；固定角色年龄、发型、服装；明确走廊结构、门窗位置、光源与禁止变化项。"/></label>
 <div className="reference-gallery">{assets.filter(a=>a.status==='approved').map(a=><figure key={a.id}><img src={a.media} alt={a.name}/><figcaption>{a.name}{a.director_id?'（历史分镜）':''}</figcaption></figure>)}</div>
 {shots.map(s=><details key={s.id}><summary>{s.id} · 绑定参考与连续性状态（{bindings[s.id]?.length||0}/3）</summary><p>{s.dramatic_action}</p>{assets.filter(a=>a.status==='approved').map(a=><label className="checkbox" key={a.id}><input type="checkbox" checked={(bindings[s.id]||[]).includes(a.id)} onChange={e=>setBindings({...bindings,[s.id]:e.target.checked?[...(bindings[s.id]||[]),a.id]:(bindings[s.id]||[]).filter(x=>x!==a.id)})}/>{a.name}</label>)}<textarea value={states[s.id]||''} onChange={e=>setStates({...states,[s.id]:e.target.value})} placeholder="人物身份与服装；场景位置、道具归属；承接上一镜的动作；本镜允许的变化。"/></details>)}
 <h3>② 三镜一致性小样</h3><p>选择能覆盖同一关键人物和空间的三镜，对照检查脸部、全身服装与相邻镜头场景。这里只提供人工审核，不宣称自动判断一致性。</p>{['人物辨识','服装与空间','相邻镜头衔接'].map((label,i)=><label key={label}>{label}<select value={samples[i]||''} onChange={e=>setSamples(samples.map((s,j)=>j===i?e.target.value:s))}>{shots.map(s=><option key={s.id}>{s.id}</option>)}</select></label>)}
 <label className="checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已审核参考图、统一规范与逐镜绑定</label><button className="button secondary" disabled={busy||!confirmed} onClick={()=>send('',{expected_version:data.config?.version||0,director_version:version,style,bindings,states,samples,approved:confirmed})}>保存并锁定本版视觉设定</button>
 <p>保存后先在下方生成、审核三个小样；设定修改将使旧版产物退出当前制作流程，历史素材仍保留。</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="小样对照审核意见：人物、画风、空间和道具是否一致（至少10字）"/><button className="button primary" disabled={busy||note.length<10||!data.config} onClick={()=>send('/approve-samples',{stamp:data.stamp,confirm:true,note})}>{data.sample_passed?'小样已通过':'确认三镜一致，解锁批量制作'}</button>{message&&<p role="status">{message}</p>}</section>;
}
